---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  vars:
    keypair: bitroid
    instance_type: t2.micro
    security_group: sg-090c080efee992a15
    volume_size: 10
    region: us-west-2
    ec2_access_key: "{{ lookup('env', 'ANSIBLE_KEY') }}"
    ec2_secret_key: "{{ lookup('env', 'ANSIBLE_VAL') }}"
  roles:
    - role: charangavvala.intellipaat
      tags: molecule-idempotence-notest
